# agent-config.yaml
objectives:
  - "Keep task list concise, with tasks broken down into manageable sub-tasks."
  - "Manage long-term memory via summaries and vector embeddings to support learning and evolution."
  - "Maintain 100% test coverage on all new code."
  - "Always update documentation (README, CHANGELOG, PROGRESS.md)."
  - "Run AI code review on every patch."
  - "Summarize each merge into PROGRESS.md."

workingDirectory: "./workspace"

git:
  remoteName: "origin"
  mainBranch: "main"

ci:
  maxWaitMinutes: 15
  pollIntervalSeconds: 30

models:
  important: "claude-sonnet-4-20250514"  # For critical tasks: code generation, reviews, complex analysis
  routine: "claude-3-5-haiku-20241022"  # For routine tasks: summaries, documentation updates

memory:
  store: "./memory.db"         # (e.g. SQLite or vector DB connection string)
  summaries: "./summaries/"    # folder for per-file summaries

files:
  tasks: "./tasks.yaml"
  progress: "./PROGRESS.md"
  changelog: "./CHANGELOG.md"

dashboard:
  enabled: true
  port: 3000

research:
  enabled: true
  directory: "./research/"
  maxResearchTasks: 5
