# agent-config.yaml
objectives:
  - "Maintain 100% test coverage on all new code"
  - "Always update documentation (README, CHANGELOG, PROGRESS.md)"
  - "Run AI code review on every patch"
  - "Keep task list concise: break large tasks into sub-tasks"
  - "Summarize each merge into PROGRESS.md"
  - "Manage long-term memory via summaries and vector embeddings"
  - "Follow clean code principles and software engineering best practices"
  - "Write self-documenting code with meaningful names and clear structure"
  - "Refactor ruthlessly to eliminate technical debt"

workingDirectory: "./workspace"

git:
  remoteName: "origin"
  mainBranch: "main"

ci:
  maxWaitMinutes: 15
  pollIntervalSeconds: 30

models:
  important: "claude-sonnet-4-20250514"  # For critical tasks: code generation, reviews, complex analysis
  routine: "claude-3-5-haiku-20241022"  # For routine tasks: summaries, documentation updates

memory:
  store: "./memory.db"         # (e.g. SQLite or vector DB connection string)
  summaries: "./summaries/"    # folder for per-file summaries

files:
  tasks: "./tasks.yaml"
  progress: "./PROGRESS.md"
  changelog: "./CHANGELOG.md"

dashboard:
  enabled: true
  port: 3000

research:
  enabled: true
  directory: "./research/"
  maxResearchTasks: 5
