name: "Push to DevOps Repo"
description: "Updates deployment files and pushes to DevOps repository"

inputs:
    devops_repo_token:
        description: "Token for the DevOps repository"
        required: true

runs:
    using: "composite"
    steps:
        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Configure Git
            run: |
                git config --global user.name "GitHub Actions Bot"
                git config --global user.email "actions@github.com"
            shell: bash

        -   name: Replace image tag in deployment.yaml
            run: |
                sed -i "s/\${GITHUB_SHA}/${{ github.sha }}/g" k8s/deployment.yaml
            shell: bash

        -   name: Commit changes
            run: |
                git add k8s/*
                git commit -m "${{ github.sha }}"
            shell: bash

        -   name: Checkout seedgpt-devops
            uses: actions/checkout@v4
            with:
                repository: "SeedGPT/seedgpt-devops"
                token: ${{ inputs.devops_repo_token }}
                path: "seedgpt-devops"

        -   name: Copy files to seedgpt-devops
            run: |
                cp -r k8s/* seedgpt-devops/k8s/
            shell: bash

        -   name: Push changes to seedgpt-devops
            run: |
                cd seedgpt-devops
                git add k8s/*
                git commit -m "${{ github.sha }}"
                git push origin HEAD
            shell: bash
