name: Development Testing CI

on:
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup environment
                uses: ./.github/actions/setup

            -   name: Build
                run: npm run build

            -   name: Archive production artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: dist
                    path: dist

    test-jest:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup environment
                uses: ./.github/actions/setup

            -   name: Download build artifacts
                uses: actions/download-artifact@v4
                with:
                    name: dist
                    path: dist

            -   name: Jest tests
                run: npm run test

    test-lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup environment
                uses: ./.github/actions/setup

            -   name: Lint tests
                run: npm run lint

    spellcheck:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup environment
                uses: ./.github/actions/setup

            -   name: Run spellcheck
                run: npm run spellcheck

    test-image:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Download production artifacts
                uses: actions/download-artifact@v4
                with:
                    name: dist
                    path: dist

            -   name: Build Docker image
                uses: ./.github/actions/build-dockerfile
